name: Build

on:
  push:
    tags:
      - deploy
  workflow_dispatch:

env:
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.15.1
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: List build files
      run: |
        ls
        ls ./build
    - name: Checkout hrushikeshj.github.io
      uses: actions/checkout@v3
      with:
        repository: hrushikeshj/hrushikeshj.github.io
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: hrushikeshj.github.io

    - name: Push gh-pages brach
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm i gh-pages --save-dev
        npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
      
