# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  
env:
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.15.1
      uses: actions/setup-node@v3
      env: 
        CI: false
      with:
        node-version: 16.15.1
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: List build files
      run: |
        ls
        ls ./build
    - name: Checkout hrushikeshj.github.io
      uses: actions/checkout@v3
      with:
        repository: hrushikeshj/hrushikeshj.github.io
        path: hrushikeshj.github.io

    - name: Copy build files
      run: |
        ls
        rm ./hrushikeshj.github.io/minesweeper/* -r
        cp build/* ./hrushikeshj.github.io/minesweeper -r
        
    - name: Pushes to hrushikeshj.github.io
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: hrushikeshj.github.io/
        destination-github-username: 'hrushikeshj'
        destination-repository-name: 'hrushikeshj.github.io'
        user-email: hrushi2002j@gmail.com
        commit-message: CI ${{ github.repository }}
        target-branch: main
    
